#!/bin/bash

DOTDIR="$( cd -P "$( dirname "$0" )" && pwd )"
pushd "${DOTDIR}" &> /dev/null

echo "Installing dotfiles..."

shopt -s dotglob extglob
for DOTFILE in !(.hg|.hgsub|.hgsubstate|install|install.bat)
do 
    echo ${DOTFILE}
    TARGET="${HOME}/${DOTFILE}"
    rm -f "${TARGET}"
    ln -sf "${DOTDIR}/${DOTFILE}" "${TARGET}"
done
popd &> /dev/null

echo "Generating a dummy certificate..."

# http://mercurial.selenic.com/wiki/CACertificates
if [ ! -f /etc/hg-dummy-cert.pem ]; then
    openssl req -new -x509 -extensions v3_ca -keyout /dev/null -out dummycert.pem -days 3650
    sudo mv dummycert.pem /etc/hg-dummy-cert.pem
fi

echo "Installing extensions..."

sudo pip install -q keyring
